name: Daily-Checkin
on:
  push:
    branches: [ main ]
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *' # 北京时间每天8点0分

jobs:
  checkin:
    runs-on: ubuntu-latest
    steps:
      - name: Set time zone
        run: sudo timedatectl set-timezone 'Asia/Shanghai'

      - name: Setup go
        uses: actions/setup-go@v2

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: go mod download

      - name: Run
        run: go run main.go
        env:
          EverPhotoMobile: ${{secrets.EVER_PHOTO_MOBILE}}
          EverPhotoPassword: ${{secrets.EVER_PHOTO_PASSWORD}}
          EverPhotoToken: ${{secrets.EVER_PHOTO_TOKEN}}
          ServerChanKey: ${{secrets.SERVER_CHAN_KEY}}
